<html><head>
	<META http-equiv="content-type" content="text/html; charset=utf-8">
	<title>pyd.exception</title>
	</head><body>
	<h1>pyd.exception</h1>
	<!-- Generated by Ddoc from pyd\exception.d -->
<br><br>
<dl><dt><big>void <u>handle_exception</u>();
</big></dt>
<dd>This function first checks if a Python exception is set, and then (if one
 is) pulls it out, stuffs it in a PythonException, and throws that exception.
<br><br>
If this exception is never caught, it will be handled by the function
 wrapping template and passed right back into Python as though nothing
 happened.
 
<br><br>

</dd>
<dt><big>class <u>PythonException</u>: object.Exception;
</big></dt>
<dd>This simple exception class holds a Python exception.
 
<br><br>

<dl></dl>
</dd>
</dl>

	<hr><small>Page generated by <a href="http://www.digitalmars.com/d/ddoc.html">Ddoc</a>. </small>
	</body></html>
